### ISSUE TITLE
Prevent user duplication

### ISSUE THREAD

**Issue by RobertAReedy** [cshepscorp/pokegen#23]
there's only enough room in the world for one akechi

**Comment by mtlankenau** [comment]
Done!

username column has unique identifier established in User.js model (unique: true). If user tries to create a new account with a username that already exists in the database, they will receive an error. Please see below: 

User.init(
  {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true,
      autoIncrement: true
    },
    username: {
      type: DataTypes.STRING(20),
      allowNull: false,
      **unique: true**
