### ISSUE TITLE
Add ability to edit username and password

### ISSUE THREAD

**Issue by RobertAReedy** [cshepscorp/pokegen#27]

**Comment by mtlankenau** [comment]
Complete! 

* Once a user is logged in, they see a "Update Account" link in the navbar
* Once clicked, user is redirected to a new handlebars page where they can edit their account info
* "New Username" input field automatically populates with the user's current username. "Password" input field is left blank
* Once fields are filled out and "Submit Change" button is clicked, user is redirected to home page
* PUT route for users is successful: user can only log back in using the new username and password
